# Generated by Django 5.0.6 on 2026-04-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Telegram"
                    ),
                ),
                (
                    "vk",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="VK"
                    ),
                ),
                (
                    "yandex",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Яндекс Мессенджер",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
    ]
