# Generated by Django 5.0.6 on 2026-04-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="attendance",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Посещаемость"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="group",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Группа"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="payments",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Платежи"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="start_english_level",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Начальный уровень английского",
            ),
        ),
    ]
