# Generated by Django 4.2.25 on 2026-04-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_lead_attendance_lead_group_lead_payments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="age",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Возраст ребёнка"
            ),
        ),
    ]
